### ISSUE TITLE
Crash on Inventory Render

### ISSUE THREAD

**Issue by ghost** [Draylar/tiered#18]
Not 100% sure if its Tiered that's causing this crash, however after crafting an armor set and equipping it the game crashes on player inventory open.

`---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-12-16 12:55:14 EST
Description: Rendering entity in world

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.handler$zgk000$getArmorTexture(ArmorFeatureRenderer:594)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.getArmorTexture(ArmorFeatureRenderer:119)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmorParts(ArmorFeatureRenderer:105)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmor(ArmorFeatureRenderer:70)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:35)
    at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:22)
    at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:139)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:65)
    at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
    at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen:149)
    at net.minecraft.class_490$$Lambda$8311/952990244.run(Unknown Source)
    at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem:1439)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen:149)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawBackground(InventoryScreen:111)
    at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen:101)
    at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen:1042)
    at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen:92)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bel000$afterCrashHandled(MinecraftClient:8904)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
    at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
    at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
    at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/692331943.accept(Unknown Source)
    at java.util.HashMap$Values.forEach(HashMap.java:972)
    at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
    at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
  Entity Type: minecraft:player (net.minecraft.class_746)
  Entity ID: 8985
  Entity Name: ScarlettBlade
  Entity's Exact location: 36.35, 51.00, 172.81
  Entity's Block location: World: (36,51,172), Chunk: (at 4,3,12 in 2,10; contains blocks 32,0,160 to 47,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, -0.01, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Brain:{memories:{}},HurtByTimestamp:0,SleepTimer:0s,Attributes:[{Base:0.0d,Name:"tiered:generic.crit_chance"},{Base:4.0d,Name:"minecraft:generic.attack_speed"},{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"},{Base:0.0d,Name:"tiered:generic.dig_speed"},{Base:0.0d,Name:"minecraft:generic.armor"},{Base:0.0d,Name:"reach-entity-attributes:reach"},{Base:0.0d,Name:"minecraft:generic.luck"},{Base:0.0d,Name:"minecraft:generic.armor_toughness"},{Base:0.0d,Name:"reach-entity-attributes:attack_range"},{Base:20.0d,Name:"minecraft:generic.max_health"}],Invulnerable:0b,FallFlying:0b,cardinal_components:{"trinkets:trinkets":{"chest:cape":{id:"minecraft:air",Count:1b,tag:{}}},"origins:origin":{OriginLayers:[{Origin:"origins-classes:lumberjack",Layer:"origins-classes:class"},{Origin:"origins:avian",Layer:"origins:origin"}],HadOriginBefore:1b,Powers:[{Type:"origins:slow_falling",Data:{}},{Type:"origins-classes:tree_felling",Data:{}},{Type:"origins:tailwind",Data:{}},{Type:"origins:vegetarian",Data:{}},{Type:"origins:fresh_air",Data:{}},{Type:"origins-classes:more_planks_from_logs",Data:{}}]}},PortalCooldown:0,AbsorptionAmount:0.0f,abilities:{invulnerable:0b,mayfly:0b,instabuild:0b,walkSpeed:0.1f,mayBuild:1b,flying:0b,flySpeed:0.05f},FallDistance:0.0f,DeathTime:0s,XpSeed:0,XpTotal:153,UUID:[I;-762590639,-1766767644,-1133197314,-1230349477],Motion:[0.0d,-0.009800000190734863d,0.0d],Health:16.0f,foodSaturationLevel:0.0f,Air:300s,OnGround:1b,magnetismEnabled:1b,Rotation:[239.8523f,-26.994984f],XpLevel:9,Score:153,Pos:[36.349215956345994d,51.0d,172.8104697690075d],Fire:-20s,XpP:0.71999973f,EnderItems:[],DataVersion:2584,foodLevel:12,foodExhaustionLevel:0.0f,HurtTime:0s,SelectedItemSlot:1,Inventory:[{Slot:0b,id:"minecraft:iron_sword",Count:1b,tag:{Damage:0,Tiered:{Tier:"tiered:sharp"}}},{Slot:1b,id:"minecraft:iron_pickaxe",Count:1b,tag:{Damage:18,Tiered:{Tier:"tiered:hasteful"}}},{Slot:2b,id:"minecraft:iron_ore",Count:14b},{Slot:3b,id:"minecraft:cobblestone",Count:21b},{Slot:8b,id:"minecraft:torch",Count:42b},{Slot:9b,id:"minecraft:spider_eye",Count:2b},{Slot:10b,id:"minecraft:oak_sapling",Count:4b},{Slot:11b,id:"minecraft:oak_log",Count:4b},{Slot:12b,id:"minecraft:sugar_cane",Count:10b},{Slot:13b,id:"minecraft:crafting_table",Count:1b},{Slot:14b,id:"terrestria:redwood_log",Count:10b},{Slot:15b,id:"minecraft:rotten_flesh",Count:10b},{Slot:17b,id:"minecraft:gunpowder",Count:1b},{Slot:18b,id:"minecraft:diorite",Count:5b},{Slot:20b,id:"minecraft:arrow",Count:2b},{Slot:21b,id:"minecraft:bone",Count:1b},{Slot:22b,id:"minecraft:stick",Count:9b},{Slot:23b,id:"techreborn:ruby_gem",Count:2b},{Slot:101b,id:"minecraft:iron_leggings",Count:1b,tag:{Damage:0,Tiered:{Tier:"tiered:epic"}}},{Slot:102b,id:"minecraft:iron_chestplate",Count:1b,tag:{Damage:0,Tiered:{Tier:"tiered:rare"}}}],foodTickTimer:0}

-- Renderer details --
  Assigned renderer: net.minecraft.class_1007@9dfc9d9
  Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Rotation: 0.0
  Delta: 1.0

-- Screen render details --
  Screen name: net.minecraft.class_490
  Mouse location: Scaled: (573, 236). Absolute: (1720.000000, 708.000000)
  Screen size: Scaled: (1147, 473). Absolute: (3440, 1417). Scale factor of 3.000000

-- Affected level --
  All players: 1 total; [class_746['ScarlettBlade'/8985, l='ClientLevel', x=36.35, y=51.00, z=172.81]]
  Chunk stats: SodiumChunkCache: 546
  Level dimension: minecraft:overworld
  Level spawn location: World: (-53,64,-177), Chunk: (at 11,4,15 in -4,-12; contains blocks -64,0,-192 to -49,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 23658 game time, 23658 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 990493896 bytes (944 MB) / 2440036352 bytes (2327 MB) up to 3817865216 bytes (3641 MB)
  CPUs: 12
  JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
  Suspected Mods: Fabric Loader (fabricloader)
  Fabric Mods: antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
               anvil_fix: AnvilFix 1.1.3+build.7-1.16
               architectury: Architectury 1.1.55
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               better_mod_button: Better Mod Button 1.1.4
               betterstones: Better Stones 0.0.4
               cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
               capes: Capes 1.1.1
               cardinal-components-base: Cardinal Components API (base) 2.7.1
               cardinal-components-entity: Cardinal Components API (entities) 2.7.1
               charm: Charm 2.1.6
               charmonium: Charmonium 2.1.4
               cinderscapes: Cinderscapes 1.3.0+build.51
               cloth-api: Cloth API 1.4.9
               cloth-armor-api-v1: Cloth Armor API v1 1.4.9
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
               cloth-utils-v1: Cloth Utils v1 1.4.9
               colormatic: Colormatic 2.2.7+mc.1.16.3
               com_electronwill_night-config_core: core 3.6.2
               com_electronwill_night-config_toml: toml 3.6.2
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               cotton: Cotton 1.1.0
               cotton-cauldron: Cotton Cauldron 1.1.0
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               cotton-commons: Cotton Commons 1.0.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               croptopia: Croptopia 1.0.5-1.16.3-FABRIC
               crowdin-translate: CrowdinTranslate 1.2
               custom-fog: Custom Fog 1.2.0
               dynamicfps: Dynamic FPS 1.2.1
               extraalchemy: Extra Alchemy 1.3.1
               fabric: Fabric API 0.28.1+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.6+build.214
               fabrishot: Fabrishot 1.2.2
               fallflyinglib: FallFlyingLib 1.1.0
               fiber: fiber 0.23.0-2
               geckolib3: Geckolib 3.0.0
               gentlefawn: GentleFawn 1.1.2-MC1.16.3-fabric
               harvest: Harvest 1.2.12
               hypnos: Hypnos 0.1.1
               intotheomega: Into the Omega 1.1.2-beta-1.16.2
               jankson: Jankson 3.0.1+j1.2.0
               jumploader: Jumploader 2.1.0
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               leaf-decay: Leaf Decay 1.2.0-1.16.1
               libstructure: LibStructure 1.5
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               minecraft: Minecraft 1.16.4
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.13+build.19
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               origins: Origins 0.4.5
               origins-classes: Origins: Classes 1.1.0
               phosphor: Phosphor 0.6.0+build.7
               raisedclouds: Raised Clouds 1.0.0
               reach-entity-attributes: Reach Entity Attribute 1.0.2
               reborncore: Reborn Core 4.6.1+build.97
               roughlyenoughitems: Roughly Enough Items 5.8.9
               roughlyenoughitems-api: REI (API) 5.8.9
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.9
               roughlyenoughitems-runtime: REI (Runtime) 5.8.9
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.7.1+build.162
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               tiered: Tiered 1.2.0-beta-1.16.4
               traverse: Traverse 3.0.3+build.13
               trinkets: Trinkets 2.6.7
               trumpet-skeleton: Trumpet Skeleton 1.1.3
  Launched Version: Jumploader
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: fabric/fabric-keybindings-v0, fabric/notenoughcrashes, fabric/fabricloader, fabric/trinkets, fabric/artifice, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/lambdynlights, fabric/fabric-blockrenderlayer-v1, fabric/fabric, fabric/fabric-networking-v0, fabric/fabric-screen-handler-api-v1, fabric/modmenu, fabric/fabrishot, fabric/phosphor, fabric/fabric-tool-attribute-api-v1, fabric/roughlyenoughitems-runtime, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-language-kotlin, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/fabric-resource-loader-v0, fabric/antighost, fabric/colormatic, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-networking-api-v1, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-renderer-api-v1, fabric/lithium, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/capes, fabric/fabric-rendering-data-attachment-v1, fabric/mm, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/raisedclouds, fabric/fabric-lifecycle-events-v1, fabric/sodium, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/dynamicfps, fabric/okzoomer, fabric/fabric-networking-blockentity-v0, fabric/custom-fog, fabric/jankson, fabric/fabric-command-api-v1, fabric/cotton-commons, fabric/fabric-renderer-indigo, fabric/roughlyenoughitems, fabric/cotton-datapack, fabric/fabric-item-api-v1, fabric/slight-gui-modifications, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/better_mod_button, fabric/spruceui, fabric/smoothscrollingeverywhere, fabric/autoconfig1u, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/fabric-events-lifecycle-v0, fabric/fabric-object-builders-v0
  Current Language: English (US)
  CPU: 12x AMD Ryzen 5 3600 6-Core Processor
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

[12:56:05] [main/INFO]: Stopping!`

**Comment by ghost** [comment]
My bad, found out where the issue was. Unrelated to Tiered
